name: causality
channels:
- conda-forge
dependencies:
- python=3.8
- black
- conda
- flake8
- ipykernel
- ipython
- jupyter
- jupyter_contrib_nbextensions
- jupyterlab
- matplotlib
- mkdocs
- mypy
- nbstripout
- networkx
- numpy
- pandas
- pip
- pre-commit
- pycodestyle
- pydocstyle
- pytest
- python=3.8
- scikit-learn
- scipy
- seaborn
- statsmodels
- pip:
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mknotebooks
